version: '3'

tasks:
  format:
    cmds:
      - task: day1-format
      - task: day2-format
      - task: day3-format
      - task: day4-format

  day1:
    dir: day_01
    cmds:
      - cargo run

  day1-format:
    dir: day_01
    cmds:
      - cargo fmt

  day1-test:
    dir: day_01
    cmds:
      - cargo test

  day2:
    dir: day_02
    cmds:
      - cargo run

  day2-format:
    dir: day_02
    cmds:
      - cargo fmt

  day2-test:
    dir: day_02
    cmds:
      - cargo test

  day3:
    dir: day_03
    cmds:
      - cargo run

  day3-format:
    dir: day_03
    cmds:
      - cargo fmt

  day3-test:
    dir: day_03
    cmds:
      - cargo test

  day4:
    dir: day_04
    cmds:
      - cargo run

  day4-format:
    dir: day_04
    cmds:
      - cargo fmt

  day4-test:
    dir: day_04
    cmds:
      - cargo test
