version: '3'

tasks:
  format:
    cmds:
      - task: day1-format

  day1:
    dir: day_01
    cmds:
      - cargo run

  day1-format:
    dir: day_01
    cmds:
      - cargo fmt

  day1-test:
    dir: day_01
    cmds:
      - cargo test
